/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package ufro.proyectoges.vista;

import java.awt.event.KeyEvent;
import java.awt.event.KeyListener;
import java.awt.event.MouseEvent;
import java.awt.event.MouseListener;
import java.awt.event.MouseMotionListener;
import java.util.List;
import javax.swing.DefaultComboBoxModel;
import javax.swing.JOptionPane;
import ufro.proyectoges.backend.entidades.Monitor;
import ufro.proyectoges.backend.entidades.Persona;
import ufro.proyectoges.backend.entidades.Registrador;
import ufro.proyectoges.backend.entidades.rut.Rut;
import ufro.proyectoges.backend.entidades.temporizador.Temporizador;

/**
 * Esta ventana meneja las acciones del administrador
 *
 * @author shido
 */
public class PanelControlAdmin extends javax.swing.JFrame implements MouseListener, KeyListener, MouseMotionListener {

    private final Persona persona;

    /**
     * Creates new form PanelControlAdmin
     *
     * @param persona Persona que suar este programa
     */
    public PanelControlAdmin(Persona persona) {
        this.persona = persona;
        initComponents();
        addMouseMotionListener(this);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        buttonGroup1 = new javax.swing.ButtonGroup();
        buttonGroup2 = new javax.swing.ButtonGroup();
        buttonGroup3 = new javax.swing.ButtonGroup();
        buttonGroup4 = new javax.swing.ButtonGroup();
        panelAdmin = new javax.swing.JPanel();
        agregarRegistradorRadioButton = new javax.swing.JRadioButton();
        agregarMonitorButton = new javax.swing.JRadioButton();
        paneAgreg = new javax.swing.JPanel();
        labelNombre = new javax.swing.JLabel();
        fieldNombre = new javax.swing.JTextField();
        labelRut = new javax.swing.JLabel();
        rutFielld1 = new javax.swing.JTextField();
        rutField2 = new javax.swing.JTextField();
        claveField = new javax.swing.JTextField();
        claveLabel = new javax.swing.JLabel();
        confirmClaveLabel = new javax.swing.JLabel();
        confirmClaveField = new javax.swing.JTextField();
        confirmarNuevoJButton = new javax.swing.JButton();
        elimRegis = new javax.swing.JRadioButton();
        elimMonitor = new javax.swing.JRadioButton();
        panelElim = new javax.swing.JPanel();
        registradores = new javax.swing.JComboBox<>();
        elimRegisSeleccionado = new javax.swing.JToggleButton();
        panelModificacion = new javax.swing.JPanel();
        labelNombre2 = new javax.swing.JLabel();
        fieldNombre2 = new javax.swing.JTextField();
        labelRut2 = new javax.swing.JLabel();
        rutFielld3 = new javax.swing.JTextField();
        rutField4 = new javax.swing.JTextField();
        claveField2 = new javax.swing.JTextField();
        claveLabel2 = new javax.swing.JLabel();
        confirmClaveLabel2 = new javax.swing.JLabel();
        confirmClaveField2 = new javax.swing.JTextField();
        confirmModif = new javax.swing.JButton();
        modifDatosJCombobox = new javax.swing.JComboBox<>();
        modifRegis = new javax.swing.JRadioButton();
        modisMoni = new javax.swing.JRadioButton();
        jLabel1 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        panelAdmin.setOpaque(false);
        panelAdmin.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        agregarRegistradorRadioButton.setText("Agregar Registrador");
        agregarRegistradorRadioButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                agregarRegistradorRadioButtonActionPerformed(evt);
            }
        });
        panelAdmin.add(agregarRegistradorRadioButton, new org.netbeans.lib.awtextra.AbsoluteConstraints(32, 31, -1, -1));

        agregarMonitorButton.setText("Agregar Monitor");
        agregarMonitorButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                agregarMonitorButtonActionPerformed(evt);
            }
        });
        panelAdmin.add(agregarMonitorButton, new org.netbeans.lib.awtextra.AbsoluteConstraints(354, 31, -1, -1));

        paneAgreg.setOpaque(false);
        paneAgreg.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        labelNombre.setText("Nombre");
        paneAgreg.add(labelNombre, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 18, 52, -1));
        paneAgreg.add(fieldNombre, new org.netbeans.lib.awtextra.AbsoluteConstraints(103, 16, 358, -1));

        labelRut.setText("Rut");
        paneAgreg.add(labelRut, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 49, -1, -1));
        paneAgreg.add(rutFielld1, new org.netbeans.lib.awtextra.AbsoluteConstraints(103, 47, 151, -1));
        paneAgreg.add(rutField2, new org.netbeans.lib.awtextra.AbsoluteConstraints(260, 47, 21, -1));
        paneAgreg.add(claveField, new org.netbeans.lib.awtextra.AbsoluteConstraints(103, 78, 241, -1));

        claveLabel.setText("Clave");
        paneAgreg.add(claveLabel, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 80, -1, -1));

        confirmClaveLabel.setText("Confirme clave");
        paneAgreg.add(confirmClaveLabel, new org.netbeans.lib.awtextra.AbsoluteConstraints(19, 111, -1, -1));
        paneAgreg.add(confirmClaveField, new org.netbeans.lib.awtextra.AbsoluteConstraints(103, 109, 241, -1));

        confirmarNuevoJButton.setText("Confirmar");
        confirmarNuevoJButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                confirmarNuevoJButtonActionPerformed(evt);
            }
        });
        paneAgreg.add(confirmarNuevoJButton, new org.netbeans.lib.awtextra.AbsoluteConstraints(427, 108, -1, -1));

        panelAdmin.add(paneAgreg, new org.netbeans.lib.awtextra.AbsoluteConstraints(71, 56, -1, 140));

        elimRegis.setText("Eliminar Registrador");
        elimRegis.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                elimRegisActionPerformed(evt);
            }
        });
        panelAdmin.add(elimRegis, new org.netbeans.lib.awtextra.AbsoluteConstraints(32, 203, -1, -1));

        elimMonitor.setText("Eliminar Monitor");
        elimMonitor.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                elimMonitorActionPerformed(evt);
            }
        });
        panelAdmin.add(elimMonitor, new org.netbeans.lib.awtextra.AbsoluteConstraints(428, 203, -1, -1));

        panelElim.setOpaque(false);
        panelElim.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        registradores.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Item 1", "Item 2", "Item 3", "Item 4" }));
        panelElim.add(registradores, new org.netbeans.lib.awtextra.AbsoluteConstraints(12, 33, -1, -1));

        elimRegisSeleccionado.setText("Eliminar Seleccionado");
        elimRegisSeleccionado.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                elimRegisSeleccionadoActionPerformed(evt);
            }
        });
        panelElim.add(elimRegisSeleccionado, new org.netbeans.lib.awtextra.AbsoluteConstraints(100, 33, -1, -1));

        panelAdmin.add(panelElim, new org.netbeans.lib.awtextra.AbsoluteConstraints(136, 228, -1, -1));

        panelModificacion.setOpaque(false);
        panelModificacion.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        labelNombre2.setText("Nombre");
        panelModificacion.add(labelNombre2, new org.netbeans.lib.awtextra.AbsoluteConstraints(114, 24, 52, -1));
        panelModificacion.add(fieldNombre2, new org.netbeans.lib.awtextra.AbsoluteConstraints(204, 22, 358, -1));

        labelRut2.setText("Rut");
        panelModificacion.add(labelRut2, new org.netbeans.lib.awtextra.AbsoluteConstraints(114, 51, -1, -1));
        panelModificacion.add(rutFielld3, new org.netbeans.lib.awtextra.AbsoluteConstraints(204, 49, 151, -1));
        panelModificacion.add(rutField4, new org.netbeans.lib.awtextra.AbsoluteConstraints(367, 49, 21, -1));
        panelModificacion.add(claveField2, new org.netbeans.lib.awtextra.AbsoluteConstraints(204, 74, 241, -1));

        claveLabel2.setText("Clave");
        panelModificacion.add(claveLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(114, 76, -1, -1));

        confirmClaveLabel2.setText("Confirme clave");
        panelModificacion.add(confirmClaveLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(114, 99, -1, -1));
        panelModificacion.add(confirmClaveField2, new org.netbeans.lib.awtextra.AbsoluteConstraints(204, 99, 241, -1));

        confirmModif.setText("Confirmar");
        confirmModif.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                confirmModifActionPerformed(evt);
            }
        });
        panelModificacion.add(confirmModif, new org.netbeans.lib.awtextra.AbsoluteConstraints(277, 124, 96, -1));

        modifDatosJCombobox.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Item 1", "Item 2", "Item 3", "Item 4" }));
        modifDatosJCombobox.addItemListener(new java.awt.event.ItemListener() {
            public void itemStateChanged(java.awt.event.ItemEvent evt) {
                modifDatosJComboboxItemStateChanged(evt);
            }
        });
        panelModificacion.add(modifDatosJCombobox, new org.netbeans.lib.awtextra.AbsoluteConstraints(12, 19, -1, -1));

        panelAdmin.add(panelModificacion, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 353, -1, -1));

        modifRegis.setText("Modificar Datos Registrador");
        modifRegis.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                modifRegisActionPerformed(evt);
            }
        });
        panelAdmin.add(modifRegis, new org.netbeans.lib.awtextra.AbsoluteConstraints(32, 328, -1, -1));

        modisMoni.setText("Modificar Datos Monitor");
        modisMoni.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                modisMoniActionPerformed(evt);
            }
        });
        panelAdmin.add(modisMoni, new org.netbeans.lib.awtextra.AbsoluteConstraints(390, 328, -1, -1));

        getContentPane().add(panelAdmin, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 631, 518));

        jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/med2.jpg"))); // NOI18N
        jLabel1.setText("jLabel1");
        getContentPane().add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 670, 520));

        pack();
    }// </editor-fold>//GEN-END:initComponents
/**
     * no contiene implementaciones
     *
     *
     * @param evt .
     */
    private void agregarRegistradorRadioButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_agregarRegistradorRadioButtonActionPerformed
        // TODO add your handling code here:
        this.agregarRegistradorRadioButton.setSelected(true);
        this.agregarMonitorButton.setSelected(false);
    }//GEN-LAST:event_agregarRegistradorRadioButtonActionPerformed
    /**
     * no contiene implementaciones
     *
     *
     * @param evt .
     */
    private void agregarMonitorButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_agregarMonitorButtonActionPerformed
        // TODO add your handling code here:
        this.agregarRegistradorRadioButton.setSelected(false);
        this.agregarMonitorButton.setSelected(true);
    }//GEN-LAST:event_agregarMonitorButtonActionPerformed
    /**
     * no contiene implementaciones
     *
     *
     * @param evt .
     */
    private void fieldNombreActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_fieldNombreActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_fieldNombreActionPerformed
    /**
     * no contiene implementaciones
     *
     *
     * @param evt .
     */
    private void rutFielld1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_rutFielld1ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_rutFielld1ActionPerformed
    /**
     * no contiene implementaciones
     *
     *
     * @param evt .
     */
    private void confirmClaveFieldActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_confirmClaveFieldActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_confirmClaveFieldActionPerformed
    /**
     * no contiene implementaciones
     *
     *
     * @param evt .
     */
    private void fieldNombre2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_fieldNombre2ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_fieldNombre2ActionPerformed
    /**
     * no contiene implementaciones
     *
     *
     * @param evt .
     */
    private void rutFielld3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_rutFielld3ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_rutFielld3ActionPerformed
    /**
     * no contiene implementaciones
     *
     *
     * @param evt .
     */
    private void confirmClaveField2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_confirmClaveField2ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_confirmClaveField2ActionPerformed
    /**
     * no contiene implementaciones
     *
     *
     * @param evt .
     */
    private void modifRegisActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_modifRegisActionPerformed
        this.modifRegis.setSelected(true);
        this.modisMoni.setSelected(false);
        this.modifDatosJCombobox.setModel(new DefaultComboBoxModel<>(persona.getHerramientaPersona().obtenerRegistradores()));

    }//GEN-LAST:event_modifRegisActionPerformed

    private void elimRegisActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_elimRegisActionPerformed
        // TODO add your handling code here:
        this.elimRegis.setSelected(true);
        this.elimMonitor.setSelected(false);
        this.registradores.setModel(new DefaultComboBoxModel<>(persona.getHerramientaPersona().obtenerRegistradores()));
    }//GEN-LAST:event_elimRegisActionPerformed

    private void elimMonitorActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_elimMonitorActionPerformed
        // TODO add your handling code here:
        this.elimRegis.setSelected(false);
        this.elimMonitor.setSelected(true);
        this.registradores.setModel(new DefaultComboBoxModel<>(persona.getHerramientaPersona().obtenerMonitores()));
    }//GEN-LAST:event_elimMonitorActionPerformed

    private void elimRegisSeleccionadoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_elimRegisSeleccionadoActionPerformed
        // TODO add your handling code here:
        if (elimRegis.isSelected()) {
            this.persona.getHerramientaPersona().eliminarRegistrador(registradores.getSelectedItem().toString());
        } else if (elimMonitor.isSelected()) {
            this.persona.getHerramientaPersona().eliminarMonitor(registradores.getSelectedItem().toString());
        }
    }//GEN-LAST:event_elimRegisSeleccionadoActionPerformed

    private void modisMoniActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_modisMoniActionPerformed
        this.modifRegis.setSelected(true);
        this.modisMoni.setSelected(false);
        this.modifDatosJCombobox.setModel(new DefaultComboBoxModel<>(persona.getHerramientaPersona().obtenerMonitores()));
    }//GEN-LAST:event_modisMoniActionPerformed

    private void confirmModifActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_confirmModifActionPerformed
        if (claveField2.getText().equalsIgnoreCase(confirmClaveField2.getText())) {
            if (modifRegis.isSelected()) {
                this.persona.getHerramientaPersona()
                        .actualizarDatosRegistrador(
                                new Registrador(
                                        Integer.parseInt(
                                                this.rutFielld3.getText() + "" + this.rutField4.getText()),
                                        this.fieldNombre2.getText(),
                                        new Rut(
                                                this.rutFielld3.getText() + "" + this.rutField4.getText()),
                                        this.claveField2.getText()));
            } else if (modisMoni.isSelected()) {
                this.persona.getHerramientaPersona()
                        .actualizarDatosMonitor(
                                new Monitor(
                                        Integer.parseInt(
                                                this.rutFielld3.getText() + "" + this.rutField4.getText()),
                                        this.fieldNombre2.getText(),
                                        new Rut(
                                                this.rutFielld3.getText() + "" + this.rutField4.getText()),
                                        this.claveField2.getText()));
            }
        } else {
            JOptionPane.showMessageDialog(null, "Las claves no coinciden",
                    "Error de claves",
                    JOptionPane.ERROR_MESSAGE);
        }
    }//GEN-LAST:event_confirmModifActionPerformed

    private void modifDatosJComboboxItemStateChanged(java.awt.event.ItemEvent evt) {//GEN-FIRST:event_modifDatosJComboboxItemStateChanged
        if (modifRegis.isSelected()) {
            List<Registrador> registradores = this.persona.getHerramientaPersona().obtenerListaRegistradores();
            for (Registrador registradore : registradores) {
                if (modifDatosJCombobox.getSelectedItem().toString().contains(registradore.getNombre())) {
                    fieldNombre2.setText(registradore.getNombre());
                    rutFielld3.setText(registradore.getRut().getRut());
                    rutField4.setText("" + registradore.getRut().obtenerDigitoVerificado());
                    claveField2.setText(registradore.getClave());
                }
            }
        } else if (modisMoni.isSelected()) {
            List<Monitor> monitores = this.persona.getHerramientaPersona().obtenerListaMonitores();
            for (Monitor monitor : monitores) {
                if (modifDatosJCombobox.getSelectedItem().toString().contains(monitor.getNombre())) {
                    fieldNombre2.setText(monitor.getNombre());
                    rutFielld3.setText(monitor.getRut().getRut());
                    rutField4.setText("" + monitor.getRut().obtenerDigitoVerificado());
                    claveField2.setText(monitor.getClave());
                }
            }
        }


    }//GEN-LAST:event_modifDatosJComboboxItemStateChanged

    private void confirmarNuevoJButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_confirmarNuevoJButtonActionPerformed
        if (confirmClaveField.getText().equalsIgnoreCase(claveField.getText())) {
            if (agregarRegistradorRadioButton.isSelected()) {
                this.persona.getHerramientaPersona().registrarRegistrador(new Registrador(
                        Integer.parseInt(
                                this.rutFielld1.getText() + "" + this.rutField2.getText()),
                        this.fieldNombre.getText(),
                        new Rut(
                                this.rutFielld1.getText() + "" + this.rutField2.getText()),
                        this.claveField.getText()));
            } else if (agregarMonitorButton.isSelected()) {
                this.persona.getHerramientaPersona().registrarMonitor(new Monitor(
                        Integer.parseInt(
                                this.rutFielld3.getText() + "" + this.rutField4.getText()),
                        this.fieldNombre2.getText(),
                        new Rut(
                                this.rutFielld3.getText() + "" + this.rutField4.getText()),
                        this.claveField2.getText()));
            }
        } else {
            JOptionPane.showMessageDialog(null, "La claves no coinciden, por favor verifique que sean iguales",
                    "Error de claves",
                    JOptionPane.ERROR_MESSAGE);
        }
    }//GEN-LAST:event_confirmarNuevoJButtonActionPerformed

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JRadioButton agregarMonitorButton;
    private javax.swing.JRadioButton agregarRegistradorRadioButton;
    private javax.swing.ButtonGroup buttonGroup1;
    private javax.swing.ButtonGroup buttonGroup2;
    private javax.swing.ButtonGroup buttonGroup3;
    private javax.swing.ButtonGroup buttonGroup4;
    private javax.swing.JTextField claveField;
    private javax.swing.JTextField claveField2;
    private javax.swing.JLabel claveLabel;
    private javax.swing.JLabel claveLabel2;
    private javax.swing.JTextField confirmClaveField;
    private javax.swing.JTextField confirmClaveField2;
    private javax.swing.JLabel confirmClaveLabel;
    private javax.swing.JLabel confirmClaveLabel2;
    private javax.swing.JButton confirmModif;
    private javax.swing.JButton confirmarNuevoJButton;
    private javax.swing.JRadioButton elimMonitor;
    private javax.swing.JRadioButton elimRegis;
    private javax.swing.JToggleButton elimRegisSeleccionado;
    private javax.swing.JTextField fieldNombre;
    private javax.swing.JTextField fieldNombre2;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel labelNombre;
    private javax.swing.JLabel labelNombre2;
    private javax.swing.JLabel labelRut;
    private javax.swing.JLabel labelRut2;
    private javax.swing.JComboBox<String> modifDatosJCombobox;
    private javax.swing.JRadioButton modifRegis;
    private javax.swing.JRadioButton modisMoni;
    private javax.swing.JPanel paneAgreg;
    private javax.swing.JPanel panelAdmin;
    private javax.swing.JPanel panelElim;
    private javax.swing.JPanel panelModificacion;
    private javax.swing.JComboBox<String> registradores;
    private javax.swing.JTextField rutField2;
    private javax.swing.JTextField rutField4;
    private javax.swing.JTextField rutFielld1;
    private javax.swing.JTextField rutFielld3;
    // End of variables declaration//GEN-END:variables

    @Override
    public void mouseClicked(MouseEvent e) {
        Temporizador.resetTemporizador(this);
    }

    @Override
    public void mousePressed(MouseEvent e) {
        Temporizador.resetTemporizador(this);
    }

    @Override
    public void mouseReleased(MouseEvent e) {
        Temporizador.resetTemporizador(this);
    }

    @Override
    public void mouseEntered(MouseEvent e) {
        Temporizador.resetTemporizador(this);
    }

    @Override
    public void mouseExited(MouseEvent e) {
        Temporizador.resetTemporizador(this);
    }

    @Override
    public void keyTyped(KeyEvent e) {
        Temporizador.resetTemporizador(this);
    }

    @Override
    public void keyPressed(KeyEvent e) {
        Temporizador.resetTemporizador(this);
    }

    @Override
    public void keyReleased(KeyEvent e) {
        Temporizador.resetTemporizador(this);
    }

    @Override
    public void mouseDragged(MouseEvent e) {
        Temporizador.resetTemporizador(this);
    }

    @Override
    public void mouseMoved(MouseEvent e) {
        Temporizador.resetTemporizador(this);
    }
}
