/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package ufro.proyectoges.vista;

import ufro.proyectoges.backend.entidades.Persona;

/**
 *
 * @author Roald
 */
public class DescargabaseDatos extends javax.swing.JFrame {

    private final Persona p;

    /**
     * Creates new form DescargabaseDatos
     * @param p
     */
    public DescargabaseDatos(Persona p) {
        this.p = p;
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        TituloJLabel = new javax.swing.JLabel();
        DescargaBaseDatosJLabel = new javax.swing.JLabel();
        CasosVigentesJButton = new javax.swing.JButton();
        CasosExceptuadosJButton = new javax.swing.JButton();
        CasosCerradosJButton = new javax.swing.JButton();
        DiaFechaInicialCasosVigentesJTextField = new javax.swing.JTextField();
        MesFechaInicialCasosVigentesJTextField = new javax.swing.JTextField();
        AnioFechaInicialCasosVigentesJTextField = new javax.swing.JTextField();
        RangoFechaInicialJLabel = new javax.swing.JLabel();
        DiaFechaFinalCasosVigentesJTextField = new javax.swing.JTextField();
        MesFechaFinalCasosVigentesJTextField = new javax.swing.JTextField();
        AnioFechaFinalCasosVigentesJTextField = new javax.swing.JTextField();
        RangoFechaFinalJLabel = new javax.swing.JLabel();
        DiaFechaInicialCasosExceptuadosJTextField = new javax.swing.JTextField();
        MesFechaInicialCasosExceptuadosJTextField = new javax.swing.JTextField();
        AnioFechaInicialCasosExceptuadosJTextField = new javax.swing.JTextField();
        RangoFechaInicialCasosExceptuados = new javax.swing.JLabel();
        DiaFechaFinalCasosExceptuadosJTextField = new javax.swing.JTextField();
        MesFechaFinalCasosExceptuadosJTextField = new javax.swing.JTextField();
        AnioFechaFinalCasosExceptuadosJTextField = new javax.swing.JTextField();
        RangoFechaFinalCasosExceptuadosJLabel = new javax.swing.JLabel();
        DiaFechaInicialCasosCerradosJTextField = new javax.swing.JTextField();
        MesFechaInicialCasosCerradosJTextField = new javax.swing.JTextField();
        AnioFechaInicialCasosCerradosJTextField = new javax.swing.JTextField();
        RangoFechaInicialCasosCerradosJLabel = new javax.swing.JLabel();
        DiaFechaFinalCasosCerradosJTextField = new javax.swing.JTextField();
        MesFechaFinalCasosCerradosJTextField = new javax.swing.JTextField();
        AnioFechaFinalCasosCerradosJTextField = new javax.swing.JTextField();
        RangoFechaFinalCasosCerradosJLabel = new javax.swing.JLabel();
        DescargaJButton = new javax.swing.JButton();
        VolverJButton = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setTitle("ProyectoGES - Descarga de Base de Datos de Casos de Pacientes");

        TituloJLabel.setFont(new java.awt.Font("Dialog", 0, 24)); // NOI18N
        TituloJLabel.setText("Sigges");

        DescargaBaseDatosJLabel.setFont(new java.awt.Font("Dialog", 0, 18)); // NOI18N
        DescargaBaseDatosJLabel.setText("Descarga de Base de Datos de Casos de Pacientes");

        CasosVigentesJButton.setText("Casos Vigentes");
        CasosVigentesJButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                CasosVigentesJButtonActionPerformed(evt);
            }
        });

        CasosExceptuadosJButton.setText("Casos Exceptuados");
        CasosExceptuadosJButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                CasosExceptuadosJButtonActionPerformed(evt);
            }
        });

        CasosCerradosJButton.setText("Casos Cerrados");
        CasosCerradosJButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                CasosCerradosJButtonActionPerformed(evt);
            }
        });

        DiaFechaInicialCasosVigentesJTextField.setEnabled(false);

        MesFechaInicialCasosVigentesJTextField.setEnabled(false);

        AnioFechaInicialCasosVigentesJTextField.setEnabled(false);

        RangoFechaInicialJLabel.setText("Rango Fecha Incial");
        RangoFechaInicialJLabel.setEnabled(false);

        DiaFechaFinalCasosVigentesJTextField.setEnabled(false);

        MesFechaFinalCasosVigentesJTextField.setEnabled(false);

        AnioFechaFinalCasosVigentesJTextField.setEnabled(false);

        RangoFechaFinalJLabel.setText("Rango Fecha Final");
        RangoFechaFinalJLabel.setEnabled(false);

        DiaFechaInicialCasosExceptuadosJTextField.setEnabled(false);

        MesFechaInicialCasosExceptuadosJTextField.setEnabled(false);

        AnioFechaInicialCasosExceptuadosJTextField.setEnabled(false);

        RangoFechaInicialCasosExceptuados.setText("Rango Fecha Incial");
        RangoFechaInicialCasosExceptuados.setEnabled(false);

        DiaFechaFinalCasosExceptuadosJTextField.setEnabled(false);

        MesFechaFinalCasosExceptuadosJTextField.setEnabled(false);

        AnioFechaFinalCasosExceptuadosJTextField.setEnabled(false);

        RangoFechaFinalCasosExceptuadosJLabel.setText("Rango Fecha Final");
        RangoFechaFinalCasosExceptuadosJLabel.setEnabled(false);

        DiaFechaInicialCasosCerradosJTextField.setEnabled(false);

        MesFechaInicialCasosCerradosJTextField.setEnabled(false);

        AnioFechaInicialCasosCerradosJTextField.setEnabled(false);

        RangoFechaInicialCasosCerradosJLabel.setText("Rango Fecha Incial");
        RangoFechaInicialCasosCerradosJLabel.setEnabled(false);

        DiaFechaFinalCasosCerradosJTextField.setEnabled(false);

        MesFechaFinalCasosCerradosJTextField.setEnabled(false);

        AnioFechaFinalCasosCerradosJTextField.setEnabled(false);

        RangoFechaFinalCasosCerradosJLabel.setText("Rango Fecha Final");
        RangoFechaFinalCasosCerradosJLabel.setEnabled(false);

        DescargaJButton.setText("Descargar");
        DescargaJButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                DescargaJButtonActionPerformed(evt);
            }
        });

        VolverJButton.setText("Volver");
        VolverJButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                VolverJButtonActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(57, 57, 57)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addComponent(CasosVigentesJButton)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(CasosCerradosJButton)
                        .addGap(55, 55, 55))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(200, 200, 200)
                        .addComponent(DescargaJButton)
                        .addGap(27, 27, 27)
                        .addComponent(VolverJButton)
                        .addGap(65, 269, Short.MAX_VALUE))))
            .addGroup(layout.createSequentialGroup()
                .addGap(312, 312, 312)
                .addComponent(TituloJLabel)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addGap(0, 0, Short.MAX_VALUE)
                .addComponent(DescargaBaseDatosJLabel)
                .addGap(141, 141, 141))
            .addGroup(layout.createSequentialGroup()
                .addGap(24, 24, 24)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(41, 41, 41)
                        .addComponent(RangoFechaInicialJLabel))
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addGroup(layout.createSequentialGroup()
                            .addGap(41, 41, 41)
                            .addComponent(RangoFechaFinalJLabel))
                        .addGroup(layout.createSequentialGroup()
                            .addGap(2, 2, 2)
                            .addComponent(DiaFechaFinalCasosVigentesJTextField, javax.swing.GroupLayout.PREFERRED_SIZE, 46, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                            .addComponent(MesFechaFinalCasosVigentesJTextField, javax.swing.GroupLayout.PREFERRED_SIZE, 43, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                            .addComponent(AnioFechaFinalCasosVigentesJTextField, javax.swing.GroupLayout.PREFERRED_SIZE, 58, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                            .addComponent(DiaFechaInicialCasosVigentesJTextField, javax.swing.GroupLayout.PREFERRED_SIZE, 46, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                            .addComponent(MesFechaInicialCasosVigentesJTextField, javax.swing.GroupLayout.PREFERRED_SIZE, 47, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                            .addComponent(AnioFechaInicialCasosVigentesJTextField, javax.swing.GroupLayout.PREFERRED_SIZE, 56, javax.swing.GroupLayout.PREFERRED_SIZE))))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(15, 15, 15)
                        .addComponent(CasosExceptuadosJButton))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(32, 32, 32)
                        .addComponent(RangoFechaInicialCasosExceptuados))
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addGroup(layout.createSequentialGroup()
                            .addComponent(DiaFechaInicialCasosExceptuadosJTextField, javax.swing.GroupLayout.PREFERRED_SIZE, 45, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                            .addComponent(MesFechaInicialCasosExceptuadosJTextField, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                            .addComponent(AnioFechaInicialCasosExceptuadosJTextField, javax.swing.GroupLayout.PREFERRED_SIZE, 52, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGroup(layout.createSequentialGroup()
                            .addComponent(DiaFechaFinalCasosExceptuadosJTextField, javax.swing.GroupLayout.PREFERRED_SIZE, 45, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                            .addComponent(MesFechaFinalCasosExceptuadosJTextField, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                            .addComponent(AnioFechaFinalCasosExceptuadosJTextField, javax.swing.GroupLayout.PREFERRED_SIZE, 51, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                            .addComponent(RangoFechaFinalCasosExceptuadosJLabel)
                            .addGap(38, 38, 38))))
                .addGap(70, 70, 70)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addGap(46, 46, 46)
                        .addComponent(RangoFechaInicialCasosCerradosJLabel)
                        .addGap(35, 35, 35))
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                        .addGroup(layout.createSequentialGroup()
                            .addComponent(RangoFechaFinalCasosCerradosJLabel)
                            .addGap(45, 45, 45))
                        .addGroup(layout.createSequentialGroup()
                            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                .addComponent(DiaFechaInicialCasosCerradosJTextField, javax.swing.GroupLayout.PREFERRED_SIZE, 48, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addComponent(DiaFechaFinalCasosCerradosJTextField, javax.swing.GroupLayout.PREFERRED_SIZE, 48, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                .addGroup(layout.createSequentialGroup()
                                    .addComponent(MesFechaInicialCasosCerradosJTextField, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                    .addComponent(AnioFechaInicialCasosCerradosJTextField, javax.swing.GroupLayout.PREFERRED_SIZE, 62, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addGroup(layout.createSequentialGroup()
                                    .addComponent(MesFechaFinalCasosCerradosJTextField, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                    .addComponent(AnioFechaFinalCasosCerradosJTextField, javax.swing.GroupLayout.PREFERRED_SIZE, 62, javax.swing.GroupLayout.PREFERRED_SIZE))))))
                .addGap(27, 27, 27))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(23, 23, 23)
                .addComponent(TituloJLabel)
                .addGap(18, 18, 18)
                .addComponent(DescargaBaseDatosJLabel)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(36, 36, 36)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(CasosVigentesJButton)
                            .addComponent(CasosCerradosJButton)))
                    .addGroup(layout.createSequentialGroup()
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(CasosExceptuadosJButton)))
                .addGap(40, 40, 40)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(RangoFechaInicialCasosCerradosJLabel)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(MesFechaInicialCasosCerradosJTextField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(AnioFechaInicialCasosCerradosJTextField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(DiaFechaInicialCasosCerradosJTextField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(RangoFechaFinalCasosCerradosJLabel)
                        .addGap(17, 17, 17)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(MesFechaFinalCasosCerradosJTextField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(AnioFechaFinalCasosCerradosJTextField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(DiaFechaFinalCasosCerradosJTextField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(DiaFechaInicialCasosExceptuadosJTextField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(MesFechaInicialCasosExceptuadosJTextField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(AnioFechaInicialCasosExceptuadosJTextField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(11, 11, 11)
                        .addComponent(RangoFechaFinalCasosExceptuadosJLabel)
                        .addGap(18, 18, 18)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(DiaFechaFinalCasosExceptuadosJTextField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(MesFechaFinalCasosExceptuadosJTextField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(AnioFechaFinalCasosExceptuadosJTextField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(RangoFechaInicialJLabel)
                            .addComponent(RangoFechaInicialCasosExceptuados))
                        .addGap(17, 17, 17)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(DiaFechaInicialCasosVigentesJTextField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(MesFechaInicialCasosVigentesJTextField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(AnioFechaInicialCasosVigentesJTextField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(RangoFechaFinalJLabel)
                        .addGap(18, 18, 18)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(DiaFechaFinalCasosVigentesJTextField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(MesFechaFinalCasosVigentesJTextField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(AnioFechaFinalCasosVigentesJTextField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 80, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(DescargaJButton)
                    .addComponent(VolverJButton))
                .addGap(54, 54, 54))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void DescargaJButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_DescargaJButtonActionPerformed
        // TODO add your handling code here:
        new GuardadoArchivo(p).setVisible(true);
    }//GEN-LAST:event_DescargaJButtonActionPerformed

    private void VolverJButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_VolverJButtonActionPerformed
        // TODO add your handling code here:
        new Menu(p).setVisible(true);
        this.dispose();
    }//GEN-LAST:event_VolverJButtonActionPerformed

    private void CasosVigentesJButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_CasosVigentesJButtonActionPerformed
        // TODO add your handling code here:
        DiaFechaInicialCasosCerradosJTextField.setEnabled(false);
        MesFechaInicialCasosCerradosJTextField.setEnabled(false);
        AnioFechaInicialCasosCerradosJTextField.setEnabled(false);
        RangoFechaInicialCasosCerradosJLabel.setEnabled(false);
        DiaFechaFinalCasosCerradosJTextField.setEnabled(false);
        MesFechaFinalCasosCerradosJTextField.setEnabled(false);
        AnioFechaFinalCasosCerradosJTextField.setEnabled(false);
        RangoFechaFinalCasosCerradosJLabel.setEnabled(false);
        
        DiaFechaInicialCasosExceptuadosJTextField.setEnabled(false);
        MesFechaInicialCasosExceptuadosJTextField.setEnabled(false);
        AnioFechaInicialCasosExceptuadosJTextField.setEnabled(false);
        RangoFechaInicialCasosExceptuados.setEnabled(false);
        DiaFechaFinalCasosExceptuadosJTextField.setEnabled(false);
        MesFechaFinalCasosExceptuadosJTextField.setEnabled(false);
        AnioFechaFinalCasosExceptuadosJTextField.setEnabled(false);
        RangoFechaFinalCasosExceptuadosJLabel.setEnabled(false);
        
        DiaFechaInicialCasosVigentesJTextField.setEnabled(true);
        MesFechaInicialCasosVigentesJTextField.setEnabled(true);
        AnioFechaInicialCasosVigentesJTextField.setEnabled(true);
        RangoFechaInicialJLabel.setEnabled(true);
        DiaFechaFinalCasosVigentesJTextField.setEnabled(true);
        MesFechaFinalCasosVigentesJTextField.setEnabled(true);
        AnioFechaFinalCasosVigentesJTextField.setEnabled(true);
        RangoFechaFinalJLabel.setEnabled(true);
    }//GEN-LAST:event_CasosVigentesJButtonActionPerformed

    private void CasosExceptuadosJButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_CasosExceptuadosJButtonActionPerformed
        // TODO add your handling code here:
        DiaFechaInicialCasosCerradosJTextField.setEnabled(false);
        MesFechaInicialCasosCerradosJTextField.setEnabled(false);
        AnioFechaInicialCasosCerradosJTextField.setEnabled(false);
        RangoFechaInicialCasosCerradosJLabel.setEnabled(false);
        DiaFechaFinalCasosCerradosJTextField.setEnabled(false);
        MesFechaFinalCasosCerradosJTextField.setEnabled(false);
        AnioFechaFinalCasosCerradosJTextField.setEnabled(false);
        RangoFechaFinalCasosCerradosJLabel.setEnabled(false);
        
        DiaFechaInicialCasosExceptuadosJTextField.setEnabled(true);
        MesFechaInicialCasosExceptuadosJTextField.setEnabled(true);
        AnioFechaInicialCasosExceptuadosJTextField.setEnabled(true);
        RangoFechaInicialCasosExceptuados.setEnabled(true);
        DiaFechaFinalCasosExceptuadosJTextField.setEnabled(true);
        MesFechaFinalCasosExceptuadosJTextField.setEnabled(true);
        AnioFechaFinalCasosExceptuadosJTextField.setEnabled(true);
        RangoFechaFinalCasosExceptuadosJLabel.setEnabled(true);
        
        DiaFechaInicialCasosVigentesJTextField.setEnabled(false);
        MesFechaInicialCasosVigentesJTextField.setEnabled(false);
        AnioFechaInicialCasosVigentesJTextField.setEnabled(false);
        RangoFechaInicialJLabel.setEnabled(false);
        DiaFechaFinalCasosVigentesJTextField.setEnabled(false);
        MesFechaFinalCasosVigentesJTextField.setEnabled(false);
        AnioFechaFinalCasosVigentesJTextField.setEnabled(false);
        RangoFechaFinalJLabel.setEnabled(false);
        
    }//GEN-LAST:event_CasosExceptuadosJButtonActionPerformed

    private void CasosCerradosJButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_CasosCerradosJButtonActionPerformed
        // TODO add your handling code here:
        DiaFechaInicialCasosExceptuadosJTextField.setEnabled(false);
        MesFechaInicialCasosExceptuadosJTextField.setEnabled(false);
        AnioFechaInicialCasosExceptuadosJTextField.setEnabled(false);
        RangoFechaInicialCasosExceptuados.setEnabled(false);
        DiaFechaFinalCasosExceptuadosJTextField.setEnabled(false);
        MesFechaFinalCasosExceptuadosJTextField.setEnabled(false);
        AnioFechaFinalCasosExceptuadosJTextField.setEnabled(false);
        RangoFechaFinalCasosExceptuadosJLabel.setEnabled(false);
        
        DiaFechaInicialCasosVigentesJTextField.setEnabled(false);
        MesFechaInicialCasosVigentesJTextField.setEnabled(false);
        AnioFechaInicialCasosVigentesJTextField.setEnabled(false);
        RangoFechaInicialJLabel.setEnabled(false);
        DiaFechaFinalCasosVigentesJTextField.setEnabled(false);
        MesFechaFinalCasosVigentesJTextField.setEnabled(false);
        AnioFechaFinalCasosVigentesJTextField.setEnabled(false);
        RangoFechaFinalJLabel.setEnabled(false);
        
        DiaFechaInicialCasosCerradosJTextField.setEnabled(true);
        MesFechaInicialCasosCerradosJTextField.setEnabled(true);
        AnioFechaInicialCasosCerradosJTextField.setEnabled(true);
        RangoFechaInicialCasosCerradosJLabel.setEnabled(true);
        DiaFechaFinalCasosCerradosJTextField.setEnabled(true);
        MesFechaFinalCasosCerradosJTextField.setEnabled(true);
        AnioFechaFinalCasosCerradosJTextField.setEnabled(true);
        RangoFechaFinalCasosCerradosJLabel.setEnabled(true);
    }//GEN-LAST:event_CasosCerradosJButtonActionPerformed

    /**
     * @param args the command line arguments
     */
   

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JTextField AnioFechaFinalCasosCerradosJTextField;
    private javax.swing.JTextField AnioFechaFinalCasosExceptuadosJTextField;
    private javax.swing.JTextField AnioFechaFinalCasosVigentesJTextField;
    private javax.swing.JTextField AnioFechaInicialCasosCerradosJTextField;
    private javax.swing.JTextField AnioFechaInicialCasosExceptuadosJTextField;
    private javax.swing.JTextField AnioFechaInicialCasosVigentesJTextField;
    private javax.swing.JButton CasosCerradosJButton;
    private javax.swing.JButton CasosExceptuadosJButton;
    private javax.swing.JButton CasosVigentesJButton;
    private javax.swing.JLabel DescargaBaseDatosJLabel;
    private javax.swing.JButton DescargaJButton;
    private javax.swing.JTextField DiaFechaFinalCasosCerradosJTextField;
    private javax.swing.JTextField DiaFechaFinalCasosExceptuadosJTextField;
    private javax.swing.JTextField DiaFechaFinalCasosVigentesJTextField;
    private javax.swing.JTextField DiaFechaInicialCasosCerradosJTextField;
    private javax.swing.JTextField DiaFechaInicialCasosExceptuadosJTextField;
    private javax.swing.JTextField DiaFechaInicialCasosVigentesJTextField;
    private javax.swing.JTextField MesFechaFinalCasosCerradosJTextField;
    private javax.swing.JTextField MesFechaFinalCasosExceptuadosJTextField;
    private javax.swing.JTextField MesFechaFinalCasosVigentesJTextField;
    private javax.swing.JTextField MesFechaInicialCasosCerradosJTextField;
    private javax.swing.JTextField MesFechaInicialCasosExceptuadosJTextField;
    private javax.swing.JTextField MesFechaInicialCasosVigentesJTextField;
    private javax.swing.JLabel RangoFechaFinalCasosCerradosJLabel;
    private javax.swing.JLabel RangoFechaFinalCasosExceptuadosJLabel;
    private javax.swing.JLabel RangoFechaFinalJLabel;
    private javax.swing.JLabel RangoFechaInicialCasosCerradosJLabel;
    private javax.swing.JLabel RangoFechaInicialCasosExceptuados;
    private javax.swing.JLabel RangoFechaInicialJLabel;
    private javax.swing.JLabel TituloJLabel;
    private javax.swing.JButton VolverJButton;
    // End of variables declaration//GEN-END:variables
}
