/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package ufro.proyectoges.vista;

/**
 *
 * @author Roald
 */
public class DescargabaseDatos extends javax.swing.JFrame {

    /**
     * Creates new form DescargabaseDatos
     */
    public DescargabaseDatos() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        TituloJLabel = new javax.swing.JLabel();
        DescargaBaseDatosJLabel = new javax.swing.JLabel();
        CasosVigentesJButton = new javax.swing.JButton();
        CasosExceptuadosJButton = new javax.swing.JButton();
        CasosCerradosJButton = new javax.swing.JButton();
        DiaFechaInicialCasosVigentesJTextField = new javax.swing.JTextField();
        MesFechaInicialCasosVigentesJTextField = new javax.swing.JTextField();
        AnioFechaInicialCasosVigentesJTextField = new javax.swing.JTextField();
        RangoFechaInicialJLabel = new javax.swing.JLabel();
        DiaFechaFinalCasosVigentesJTextField = new javax.swing.JTextField();
        MesFechaFinalCasosVigentesJTextField = new javax.swing.JTextField();
        AnioFechaFinalCasosVigentesJTextField = new javax.swing.JTextField();
        RangoFechaFinalJLabel = new javax.swing.JLabel();
        DiaFechaInicialCasosExceptuadosJTextField = new javax.swing.JTextField();
        MesFechaInicialCasosExceptuadosJTextField = new javax.swing.JTextField();
        AnioFechaInicialCasosExceptuadosJTextField = new javax.swing.JTextField();
        RangoFechaInicialCasosExceptuados = new javax.swing.JLabel();
        DiaFechaFinalCasosExceptuadosJTextField = new javax.swing.JTextField();
        MesFechaFinalCasosExceptuadosJTextField = new javax.swing.JTextField();
        AnioFechaFinalCasosExceptuadosJTextField = new javax.swing.JTextField();
        RangoFechaFinalCasosExceptuadosJLabel = new javax.swing.JLabel();
        DiaFechaInicialCasosCerradosJTextField = new javax.swing.JTextField();
        MesFechaInicialCasosCerradosJTextField = new javax.swing.JTextField();
        AnioFechaInicialCasosCerradosJTextField = new javax.swing.JTextField();
        RangoFechaInicialCasosCerradosJLabel = new javax.swing.JLabel();
        DiaFechaFinalCasosCerradosJTextField = new javax.swing.JTextField();
        MesFechaFinalCasosCerradosJTextField = new javax.swing.JTextField();
        AnioFechaFinalCasosCerradosJTextField = new javax.swing.JTextField();
        RangoFechaFinalCasosCerradosJLabel = new javax.swing.JLabel();
        DescargaJButton = new javax.swing.JButton();
        VolverJButton = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        TituloJLabel.setFont(new java.awt.Font("Dialog", 0, 24)); // NOI18N
        TituloJLabel.setText("Sigges");

        DescargaBaseDatosJLabel.setFont(new java.awt.Font("Dialog", 0, 18)); // NOI18N
        DescargaBaseDatosJLabel.setText("Descarga de Base de Datos de Casos de Pacientes");

        CasosVigentesJButton.setText("Casos Vigentes");

        CasosExceptuadosJButton.setText("Casos Exceptuados");

        CasosCerradosJButton.setText("Casos Cerrados");

        DiaFechaInicialCasosVigentesJTextField.setEnabled(false);

        MesFechaInicialCasosVigentesJTextField.setEnabled(false);

        AnioFechaInicialCasosVigentesJTextField.setEnabled(false);

        RangoFechaInicialJLabel.setText("Rango Fecha Incial");
        RangoFechaInicialJLabel.setEnabled(false);

        DiaFechaFinalCasosVigentesJTextField.setEnabled(false);

        MesFechaFinalCasosVigentesJTextField.setEnabled(false);

        AnioFechaFinalCasosVigentesJTextField.setEnabled(false);

        RangoFechaFinalJLabel.setText("Rango Fecha Final");
        RangoFechaFinalJLabel.setEnabled(false);

        DiaFechaInicialCasosExceptuadosJTextField.setEnabled(false);

        MesFechaInicialCasosExceptuadosJTextField.setEnabled(false);

        AnioFechaInicialCasosExceptuadosJTextField.setEnabled(false);

        RangoFechaInicialCasosExceptuados.setText("Rango Fecha Incial");
        RangoFechaInicialCasosExceptuados.setEnabled(false);

        DiaFechaFinalCasosExceptuadosJTextField.setEnabled(false);

        MesFechaFinalCasosExceptuadosJTextField.setEnabled(false);

        AnioFechaFinalCasosExceptuadosJTextField.setEnabled(false);

        RangoFechaFinalCasosExceptuadosJLabel.setText("Rango Fecha Final");
        RangoFechaFinalCasosExceptuadosJLabel.setEnabled(false);

        DiaFechaInicialCasosCerradosJTextField.setEnabled(false);

        MesFechaInicialCasosCerradosJTextField.setEnabled(false);

        AnioFechaInicialCasosCerradosJTextField.setEnabled(false);

        RangoFechaInicialCasosCerradosJLabel.setText("Rango Fecha Incial");
        RangoFechaInicialCasosCerradosJLabel.setEnabled(false);

        DiaFechaFinalCasosCerradosJTextField.setEnabled(false);

        MesFechaFinalCasosCerradosJTextField.setEnabled(false);
        MesFechaFinalCasosCerradosJTextField.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                MesFechaFinalCasosCerradosJTextFieldActionPerformed(evt);
            }
        });

        AnioFechaFinalCasosCerradosJTextField.setEnabled(false);

        RangoFechaFinalCasosCerradosJLabel.setText("Rango Fecha Final");
        RangoFechaFinalCasosCerradosJLabel.setEnabled(false);

        DescargaJButton.setText("Descargar");
        DescargaJButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                DescargaJButtonActionPerformed(evt);
            }
        });

        VolverJButton.setText("Volver");
        VolverJButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                VolverJButtonActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(57, 57, 57)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addComponent(CasosVigentesJButton)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addGap(12, 12, 12)
                                .addComponent(RangoFechaInicialCasosCerradosJLabel))
                            .addComponent(CasosCerradosJButton))
                        .addGap(55, 55, 55))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(12, 12, 12)
                        .addComponent(RangoFechaInicialJLabel)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(layout.createSequentialGroup()
                                        .addGap(102, 102, 102)
                                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                            .addGroup(layout.createSequentialGroup()
                                                .addGap(11, 11, 11)
                                                .addComponent(CasosExceptuadosJButton))
                                            .addGroup(layout.createSequentialGroup()
                                                .addComponent(DiaFechaInicialCasosExceptuadosJTextField, javax.swing.GroupLayout.PREFERRED_SIZE, 45, javax.swing.GroupLayout.PREFERRED_SIZE)
                                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                                .addComponent(MesFechaInicialCasosExceptuadosJTextField, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE)
                                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                                .addComponent(AnioFechaInicialCasosExceptuadosJTextField, javax.swing.GroupLayout.PREFERRED_SIZE, 52, javax.swing.GroupLayout.PREFERRED_SIZE))
                                            .addGroup(layout.createSequentialGroup()
                                                .addComponent(DiaFechaFinalCasosExceptuadosJTextField, javax.swing.GroupLayout.PREFERRED_SIZE, 45, javax.swing.GroupLayout.PREFERRED_SIZE)
                                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                                .addComponent(MesFechaFinalCasosExceptuadosJTextField, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE)
                                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                                .addComponent(AnioFechaFinalCasosExceptuadosJTextField, javax.swing.GroupLayout.PREFERRED_SIZE, 51, javax.swing.GroupLayout.PREFERRED_SIZE))
                                            .addGroup(layout.createSequentialGroup()
                                                .addGap(107, 107, 107)
                                                .addComponent(VolverJButton))))
                                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                                                .addComponent(RangoFechaFinalCasosExceptuadosJLabel)
                                                .addGap(38, 38, 38))
                                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                                                .addComponent(DescargaJButton)
                                                .addGap(114, 114, 114)))))
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(layout.createSequentialGroup()
                                        .addGap(71, 71, 71)
                                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                            .addComponent(DiaFechaInicialCasosCerradosJTextField, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 48, javax.swing.GroupLayout.PREFERRED_SIZE)
                                            .addComponent(DiaFechaFinalCasosCerradosJTextField, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 48, javax.swing.GroupLayout.PREFERRED_SIZE))
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                            .addGroup(layout.createSequentialGroup()
                                                .addComponent(MesFechaInicialCasosCerradosJTextField, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE)
                                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                                .addComponent(AnioFechaInicialCasosCerradosJTextField, javax.swing.GroupLayout.PREFERRED_SIZE, 62, javax.swing.GroupLayout.PREFERRED_SIZE))
                                            .addGroup(layout.createSequentialGroup()
                                                .addComponent(MesFechaFinalCasosCerradosJTextField, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE)
                                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                                .addComponent(AnioFechaFinalCasosCerradosJTextField, javax.swing.GroupLayout.PREFERRED_SIZE, 62, javax.swing.GroupLayout.PREFERRED_SIZE)))
                                        .addGap(20, 20, 20))
                                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                                        .addComponent(RangoFechaFinalCasosCerradosJLabel)
                                        .addGap(65, 65, 65))))
                            .addGroup(layout.createSequentialGroup()
                                .addGap(134, 134, 134)
                                .addComponent(RangoFechaInicialCasosExceptuados)
                                .addGap(0, 0, Short.MAX_VALUE))))))
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(69, 69, 69)
                        .addComponent(RangoFechaFinalJLabel))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(22, 22, 22)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(DiaFechaInicialCasosVigentesJTextField, javax.swing.GroupLayout.PREFERRED_SIZE, 46, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(MesFechaInicialCasosVigentesJTextField, javax.swing.GroupLayout.PREFERRED_SIZE, 47, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(AnioFechaInicialCasosVigentesJTextField, javax.swing.GroupLayout.PREFERRED_SIZE, 56, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(DiaFechaFinalCasosVigentesJTextField, javax.swing.GroupLayout.PREFERRED_SIZE, 46, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(MesFechaFinalCasosVigentesJTextField, javax.swing.GroupLayout.PREFERRED_SIZE, 43, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(AnioFechaFinalCasosVigentesJTextField, javax.swing.GroupLayout.PREFERRED_SIZE, 58, javax.swing.GroupLayout.PREFERRED_SIZE)))))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addComponent(DescargaBaseDatosJLabel)
                        .addGap(108, 108, 108))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addComponent(TituloJLabel)
                        .addGap(296, 296, 296))))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(23, 23, 23)
                .addComponent(TituloJLabel)
                .addGap(18, 18, 18)
                .addComponent(DescargaBaseDatosJLabel)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(36, 36, 36)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(CasosVigentesJButton)
                            .addComponent(CasosCerradosJButton)))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(CasosExceptuadosJButton)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(RangoFechaInicialCasosCerradosJLabel)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(DiaFechaInicialCasosCerradosJTextField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(MesFechaInicialCasosCerradosJTextField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(AnioFechaInicialCasosCerradosJTextField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(RangoFechaFinalCasosCerradosJLabel)
                        .addGap(17, 17, 17)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(DiaFechaFinalCasosCerradosJTextField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(MesFechaFinalCasosCerradosJTextField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(AnioFechaFinalCasosCerradosJTextField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(DiaFechaInicialCasosExceptuadosJTextField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(MesFechaInicialCasosExceptuadosJTextField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(AnioFechaInicialCasosExceptuadosJTextField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(11, 11, 11)
                        .addComponent(RangoFechaFinalCasosExceptuadosJLabel)
                        .addGap(18, 18, 18)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(DiaFechaFinalCasosExceptuadosJTextField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(MesFechaFinalCasosExceptuadosJTextField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(AnioFechaFinalCasosExceptuadosJTextField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(RangoFechaInicialJLabel)
                            .addComponent(RangoFechaInicialCasosExceptuados))
                        .addGap(17, 17, 17)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(DiaFechaInicialCasosVigentesJTextField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(MesFechaInicialCasosVigentesJTextField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(AnioFechaInicialCasosVigentesJTextField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(RangoFechaFinalJLabel)
                        .addGap(18, 18, 18)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(DiaFechaFinalCasosVigentesJTextField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(MesFechaFinalCasosVigentesJTextField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(AnioFechaFinalCasosVigentesJTextField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 56, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(DescargaJButton)
                    .addComponent(VolverJButton))
                .addGap(54, 54, 54))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void DescargaJButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_DescargaJButtonActionPerformed
        // TODO add your handling code here:
        new GuardadoArchivo().setVisible(true);
    }//GEN-LAST:event_DescargaJButtonActionPerformed

    private void VolverJButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_VolverJButtonActionPerformed
        // TODO add your handling code here:
        new Menu().setVisible(true);
        this.dispose();
    }//GEN-LAST:event_VolverJButtonActionPerformed

    private void MesFechaFinalCasosCerradosJTextFieldActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_MesFechaFinalCasosCerradosJTextFieldActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_MesFechaFinalCasosCerradosJTextFieldActionPerformed

    /**
     * @param args the command line arguments
     */
   

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JTextField AnioFechaFinalCasosCerradosJTextField;
    private javax.swing.JTextField AnioFechaFinalCasosExceptuadosJTextField;
    private javax.swing.JTextField AnioFechaFinalCasosVigentesJTextField;
    private javax.swing.JTextField AnioFechaInicialCasosCerradosJTextField;
    private javax.swing.JTextField AnioFechaInicialCasosExceptuadosJTextField;
    private javax.swing.JTextField AnioFechaInicialCasosVigentesJTextField;
    private javax.swing.JButton CasosCerradosJButton;
    private javax.swing.JButton CasosExceptuadosJButton;
    private javax.swing.JButton CasosVigentesJButton;
    private javax.swing.JLabel DescargaBaseDatosJLabel;
    private javax.swing.JButton DescargaJButton;
    private javax.swing.JTextField DiaFechaFinalCasosCerradosJTextField;
    private javax.swing.JTextField DiaFechaFinalCasosExceptuadosJTextField;
    private javax.swing.JTextField DiaFechaFinalCasosVigentesJTextField;
    private javax.swing.JTextField DiaFechaInicialCasosCerradosJTextField;
    private javax.swing.JTextField DiaFechaInicialCasosExceptuadosJTextField;
    private javax.swing.JTextField DiaFechaInicialCasosVigentesJTextField;
    private javax.swing.JTextField MesFechaFinalCasosCerradosJTextField;
    private javax.swing.JTextField MesFechaFinalCasosExceptuadosJTextField;
    private javax.swing.JTextField MesFechaFinalCasosVigentesJTextField;
    private javax.swing.JTextField MesFechaInicialCasosCerradosJTextField;
    private javax.swing.JTextField MesFechaInicialCasosExceptuadosJTextField;
    private javax.swing.JTextField MesFechaInicialCasosVigentesJTextField;
    private javax.swing.JLabel RangoFechaFinalCasosCerradosJLabel;
    private javax.swing.JLabel RangoFechaFinalCasosExceptuadosJLabel;
    private javax.swing.JLabel RangoFechaFinalJLabel;
    private javax.swing.JLabel RangoFechaInicialCasosCerradosJLabel;
    private javax.swing.JLabel RangoFechaInicialCasosExceptuados;
    private javax.swing.JLabel RangoFechaInicialJLabel;
    private javax.swing.JLabel TituloJLabel;
    private javax.swing.JButton VolverJButton;
    // End of variables declaration//GEN-END:variables
}
