/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package ufro.proyectoges.vista;

import java.sql.Date;
import javax.swing.JOptionPane;
import ufro.proyectoges.backend.entidades.IPDPaciente;
import ufro.proyectoges.backend.entidades.Persona;
import ufro.proyectoges.backend.herramientas.HerramientaRegistrador;

/**
 *
 * @author Roald
 */
public class IPD extends javax.swing.JFrame {

    private final Persona p;
    private final IngresoCasoPaciente formPaciente;

    /**
     * Creates new form IPD
     *
     * @param p
     * @param formPaciente
     */
    public IPD(Persona p, IngresoCasoPaciente formPaciente) {
        this.formPaciente = formPaciente;
        this.p = p;
        initComponents();
        
        NombreCompletoJTextField.setEnabled(false);
        RUTJTextField1.setEnabled(false);
        RUTJTextField2.setEnabled(false);
        PatologiasJTextField.setEnabled(false);
        
        NombreCompletoJTextField.setText(formPaciente.getNombreJTextField().getText());
        RUTJTextField1.setText(formPaciente.getRUTJTextField1().getText());
        RUTJTextField2.setText(formPaciente.getRUTJTextField2().getText());
        PatologiasJTextField.setText(formPaciente.getPatologiasJTextField().getText());
        
        
        
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        IPDJLabel = new javax.swing.JLabel();
        NombreCompletoJLabel = new javax.swing.JLabel();
        NombreCompletoJTextField = new javax.swing.JTextField();
        RUTJLabel = new javax.swing.JLabel();
        RUTJTextField1 = new javax.swing.JTextField();
        RUTJTextField2 = new javax.swing.JTextField();
        PatologiasJLabel = new javax.swing.JLabel();
        PatologiasJTextField = new javax.swing.JTextField();
        FechaInicioJLabel = new javax.swing.JLabel();
        DiaFechaInicioJTextField = new javax.swing.JTextField();
        MesFechaInicioJTextField = new javax.swing.JTextField();
        AnioFechaInicioJTextField = new javax.swing.JTextField();
        FechaTerminoJLabel = new javax.swing.JLabel();
        DiaFechaTerminoJTextField = new javax.swing.JTextField();
        MesFechaTerminoJTextField = new javax.swing.JTextField();
        AnioFechaTerminoJTextField = new javax.swing.JTextField();
        jSeparator1 = new javax.swing.JSeparator();
        GESJCheckBox = new javax.swing.JCheckBox();
        NoGesJCheckBox = new javax.swing.JCheckBox();
        NotificacionPacienteGesJLabel = new javax.swing.JLabel();
        SiJCheckBox = new javax.swing.JCheckBox();
        NoJCheckBox = new javax.swing.JCheckBox();
        jSeparator2 = new javax.swing.JSeparator();
        jSeparator3 = new javax.swing.JSeparator();
        ConfirmadoJCheckBox = new javax.swing.JCheckBox();
        DescartadoJCheckBox = new javax.swing.JCheckBox();
        ExceptuadoJCheckBox = new javax.swing.JCheckBox();
        jSeparator4 = new javax.swing.JSeparator();
        ObservacionJLabel = new javax.swing.JLabel();
        ObservacionJScrollPane = new javax.swing.JScrollPane();
        ObservacionJTextArea = new javax.swing.JTextArea();
        AceptarJButton = new javax.swing.JButton();
        VolverJButton = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setTitle("ProyectoGES - IPD");
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        IPDJLabel.setFont(new java.awt.Font("Dialog", 0, 24)); // NOI18N
        IPDJLabel.setForeground(new java.awt.Color(0, 0, 0));
        IPDJLabel.setText("IPD");
        getContentPane().add(IPDJLabel, new org.netbeans.lib.awtextra.AbsoluteConstraints(297, 12, -1, -1));

        NombreCompletoJLabel.setForeground(new java.awt.Color(0, 0, 0));
        NombreCompletoJLabel.setText("Nombre Completo:");
        getContentPane().add(NombreCompletoJLabel, new org.netbeans.lib.awtextra.AbsoluteConstraints(32, 84, -1, -1));

        NombreCompletoJTextField.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                NombreCompletoJTextFieldActionPerformed(evt);
            }
        });
        getContentPane().add(NombreCompletoJTextField, new org.netbeans.lib.awtextra.AbsoluteConstraints(140, 80, 233, -1));

        RUTJLabel.setForeground(new java.awt.Color(0, 0, 0));
        RUTJLabel.setText("RUT");
        getContentPane().add(RUTJLabel, new org.netbeans.lib.awtextra.AbsoluteConstraints(32, 115, -1, -1));
        getContentPane().add(RUTJTextField1, new org.netbeans.lib.awtextra.AbsoluteConstraints(70, 110, 96, -1));
        getContentPane().add(RUTJTextField2, new org.netbeans.lib.awtextra.AbsoluteConstraints(180, 110, 28, -1));

        PatologiasJLabel.setForeground(new java.awt.Color(0, 0, 0));
        PatologiasJLabel.setText("Patologias:");
        getContentPane().add(PatologiasJLabel, new org.netbeans.lib.awtextra.AbsoluteConstraints(32, 152, -1, -1));
        getContentPane().add(PatologiasJTextField, new org.netbeans.lib.awtextra.AbsoluteConstraints(96, 150, 268, -1));

        FechaInicioJLabel.setForeground(new java.awt.Color(0, 0, 0));
        FechaInicioJLabel.setText("Fecha de Inicio");
        getContentPane().add(FechaInicioJLabel, new org.netbeans.lib.awtextra.AbsoluteConstraints(491, 84, -1, -1));
        getContentPane().add(DiaFechaInicioJTextField, new org.netbeans.lib.awtextra.AbsoluteConstraints(458, 101, 30, -1));
        getContentPane().add(MesFechaInicioJTextField, new org.netbeans.lib.awtextra.AbsoluteConstraints(500, 101, 29, -1));
        getContentPane().add(AnioFechaInicioJTextField, new org.netbeans.lib.awtextra.AbsoluteConstraints(547, 101, 59, -1));

        FechaTerminoJLabel.setForeground(new java.awt.Color(0, 0, 0));
        FechaTerminoJLabel.setText("Fecha de Termino");
        getContentPane().add(FechaTerminoJLabel, new org.netbeans.lib.awtextra.AbsoluteConstraints(485, 132, -1, -1));
        getContentPane().add(DiaFechaTerminoJTextField, new org.netbeans.lib.awtextra.AbsoluteConstraints(458, 150, 30, -1));
        getContentPane().add(MesFechaTerminoJTextField, new org.netbeans.lib.awtextra.AbsoluteConstraints(500, 150, 29, -1));
        getContentPane().add(AnioFechaTerminoJTextField, new org.netbeans.lib.awtextra.AbsoluteConstraints(547, 150, 59, -1));
        getContentPane().add(jSeparator1, new org.netbeans.lib.awtextra.AbsoluteConstraints(12, 187, 607, 10));

        GESJCheckBox.setFont(new java.awt.Font("Dialog", 0, 14)); // NOI18N
        GESJCheckBox.setForeground(new java.awt.Color(0, 0, 0));
        GESJCheckBox.setText("GEST");
        GESJCheckBox.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                GESJCheckBoxActionPerformed(evt);
            }
        });
        getContentPane().add(GESJCheckBox, new org.netbeans.lib.awtextra.AbsoluteConstraints(24, 203, -1, -1));

        NoGesJCheckBox.setFont(new java.awt.Font("Dialog", 0, 14)); // NOI18N
        NoGesJCheckBox.setForeground(new java.awt.Color(0, 0, 0));
        NoGesJCheckBox.setText("NO GEST");
        NoGesJCheckBox.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                NoGesJCheckBoxActionPerformed(evt);
            }
        });
        getContentPane().add(NoGesJCheckBox, new org.netbeans.lib.awtextra.AbsoluteConstraints(24, 248, -1, -1));

        NotificacionPacienteGesJLabel.setFont(new java.awt.Font("Dialog", 0, 14)); // NOI18N
        NotificacionPacienteGesJLabel.setForeground(new java.awt.Color(0, 0, 0));
        NotificacionPacienteGesJLabel.setText("Notificacion Paciente Gest");
        getContentPane().add(NotificacionPacienteGesJLabel, new org.netbeans.lib.awtextra.AbsoluteConstraints(440, 203, -1, -1));

        SiJCheckBox.setFont(new java.awt.Font("Dialog", 0, 14)); // NOI18N
        SiJCheckBox.setForeground(new java.awt.Color(0, 0, 0));
        SiJCheckBox.setText("SI");
        SiJCheckBox.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                SiJCheckBoxActionPerformed(evt);
            }
        });
        getContentPane().add(SiJCheckBox, new org.netbeans.lib.awtextra.AbsoluteConstraints(466, 248, -1, -1));

        NoJCheckBox.setFont(new java.awt.Font("Dialog", 0, 14)); // NOI18N
        NoJCheckBox.setForeground(new java.awt.Color(0, 0, 0));
        NoJCheckBox.setText("NO");
        NoJCheckBox.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                NoJCheckBoxActionPerformed(evt);
            }
        });
        getContentPane().add(NoJCheckBox, new org.netbeans.lib.awtextra.AbsoluteConstraints(529, 248, -1, -1));
        getContentPane().add(jSeparator2, new org.netbeans.lib.awtextra.AbsoluteConstraints(12, 282, 607, 10));
        getContentPane().add(jSeparator3, new org.netbeans.lib.awtextra.AbsoluteConstraints(12, 50, 607, 12));

        ConfirmadoJCheckBox.setFont(new java.awt.Font("Dialog", 0, 14)); // NOI18N
        ConfirmadoJCheckBox.setForeground(new java.awt.Color(0, 0, 0));
        ConfirmadoJCheckBox.setText("Confirmado");
        ConfirmadoJCheckBox.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ConfirmadoJCheckBoxActionPerformed(evt);
            }
        });
        getContentPane().add(ConfirmadoJCheckBox, new org.netbeans.lib.awtextra.AbsoluteConstraints(24, 300, -1, -1));

        DescartadoJCheckBox.setFont(new java.awt.Font("Dialog", 0, 14)); // NOI18N
        DescartadoJCheckBox.setForeground(new java.awt.Color(0, 0, 0));
        DescartadoJCheckBox.setText("Descartado");
        DescartadoJCheckBox.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                DescartadoJCheckBoxActionPerformed(evt);
            }
        });
        getContentPane().add(DescartadoJCheckBox, new org.netbeans.lib.awtextra.AbsoluteConstraints(24, 330, -1, -1));

        ExceptuadoJCheckBox.setFont(new java.awt.Font("Dialog", 0, 14)); // NOI18N
        ExceptuadoJCheckBox.setForeground(new java.awt.Color(0, 0, 0));
        ExceptuadoJCheckBox.setText("Exceptuado");
        getContentPane().add(ExceptuadoJCheckBox, new org.netbeans.lib.awtextra.AbsoluteConstraints(465, 300, -1, -1));
        getContentPane().add(jSeparator4, new org.netbeans.lib.awtextra.AbsoluteConstraints(12, 364, 607, 10));

        ObservacionJLabel.setForeground(new java.awt.Color(0, 0, 0));
        ObservacionJLabel.setText("Observacion:");
        getContentPane().add(ObservacionJLabel, new org.netbeans.lib.awtextra.AbsoluteConstraints(24, 380, -1, -1));

        ObservacionJTextArea.setColumns(20);
        ObservacionJTextArea.setRows(5);
        ObservacionJScrollPane.setViewportView(ObservacionJTextArea);

        getContentPane().add(ObservacionJScrollPane, new org.netbeans.lib.awtextra.AbsoluteConstraints(24, 401, 585, 98));

        AceptarJButton.setText("Aceptar");
        AceptarJButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                AceptarJButtonActionPerformed(evt);
            }
        });
        getContentPane().add(AceptarJButton, new org.netbeans.lib.awtextra.AbsoluteConstraints(202, 505, -1, -1));

        VolverJButton.setText("Volver");
        VolverJButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                VolverJButtonActionPerformed(evt);
            }
        });
        getContentPane().add(VolverJButton, new org.netbeans.lib.awtextra.AbsoluteConstraints(328, 505, -1, -1));

        jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/med2.jpg"))); // NOI18N
        jLabel1.setText("jLabel1");
        getContentPane().add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 630, 540));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void AceptarJButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_AceptarJButtonActionPerformed
        // TODO add your handling code here:

        boolean nomNoVacio = !NombreCompletoJTextField.getText().isEmpty();
        boolean rutNoVacio = !RUTJTextField1.getText().isEmpty() && !RUTJTextField2.getText().isEmpty();
        boolean fechaInNoVac = !AnioFechaInicioJTextField.getText().isEmpty() && !MesFechaInicioJTextField.getText().isEmpty() && !DiaFechaInicioJTextField.getText().isEmpty();
        boolean fechaTeNoVac = !AnioFechaTerminoJTextField.getText().isEmpty() && !MesFechaTerminoJTextField.getText().isEmpty() && !DiaFechaTerminoJTextField.getText().isEmpty();
        boolean gesONoGES = GESJCheckBox.isSelected();
        boolean notif = SiJCheckBox.isSelected() || NoJCheckBox.isSelected();
        boolean ConExDes = ConfirmadoJCheckBox.isSelected() || ExceptuadoJCheckBox.isSelected() || DescartadoJCheckBox.isSelected();
        boolean obser = !ObservacionJTextArea.getText().isEmpty();

        if (nomNoVacio && rutNoVacio && fechaInNoVac && fechaTeNoVac && gesONoGES && notif && ConExDes && obser) {
            formPaciente.setIpd(new IPDPaciente(RUTJTextField1.getText() + RUTJTextField2.getText(),
                    NombreCompletoJTextField.getText(),
                    new Date(Integer.parseInt(AnioFechaInicioJTextField.getText()),
                            Integer.parseInt(MesFechaInicioJTextField.getText()),
                            Integer.parseInt(DiaFechaInicioJTextField.getText())),
                    new Date(Integer.parseInt(AnioFechaTerminoJTextField.getText()),
                            Integer.parseInt(MesFechaTerminoJTextField.getText()),
                            Integer.parseInt(DiaFechaTerminoJTextField.getText())),
                    GESJCheckBox.isSelected(),
                    SiJCheckBox.isSelected(),
                    ConfirmadoJCheckBox.isSelected(),
                    ExceptuadoJCheckBox.isSelected(),
                    DescartadoJCheckBox.isSelected(),
                    ObservacionJTextArea.getText(),
                    0));
            formPaciente.getConfirmacionIPD().setText("IPD cargado");
            this.dispose();
        } else {
            JOptionPane.showMessageDialog(null, "Faltan campos por llenar");
        }

    }//GEN-LAST:event_AceptarJButtonActionPerformed

    private void GESJCheckBoxActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_GESJCheckBoxActionPerformed
        // TODO add your handling code here:
        GESJCheckBox.setSelected(true);
        NoGesJCheckBox.setSelected(false);
    }//GEN-LAST:event_GESJCheckBoxActionPerformed

    private void NoGesJCheckBoxActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_NoGesJCheckBoxActionPerformed
        // TODO add your handling code here:
        GESJCheckBox.setSelected(false);
        NoGesJCheckBox.setSelected(true);
    }//GEN-LAST:event_NoGesJCheckBoxActionPerformed

    private void SiJCheckBoxActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_SiJCheckBoxActionPerformed
        // TODO add your handling code here:
        SiJCheckBox.setSelected(true);
        NoJCheckBox.setSelected(false);
    }//GEN-LAST:event_SiJCheckBoxActionPerformed

    private void NoJCheckBoxActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_NoJCheckBoxActionPerformed
        // TODO add your handling code here:
        SiJCheckBox.setSelected(false);
        NoJCheckBox.setSelected(true);
    }//GEN-LAST:event_NoJCheckBoxActionPerformed

    private void ConfirmadoJCheckBoxActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ConfirmadoJCheckBoxActionPerformed
        // TODO add your handling code here:
        ConfirmadoJCheckBox.setSelected(true);
        DescartadoJCheckBox.setSelected(false);
    }//GEN-LAST:event_ConfirmadoJCheckBoxActionPerformed

    private void DescartadoJCheckBoxActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_DescartadoJCheckBoxActionPerformed
        // TODO add your handling code here:
        ConfirmadoJCheckBox.setSelected(false);
        DescartadoJCheckBox.setSelected(true);
    }//GEN-LAST:event_DescartadoJCheckBoxActionPerformed

    private void VolverJButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_VolverJButtonActionPerformed
        // TODO add your handling code here:
        this.dispose();
    }//GEN-LAST:event_VolverJButtonActionPerformed

    private void NombreCompletoJTextFieldActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_NombreCompletoJTextFieldActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_NombreCompletoJTextFieldActionPerformed

    /**
     * @param args the command line arguments
     */

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton AceptarJButton;
    private javax.swing.JTextField AnioFechaInicioJTextField;
    private javax.swing.JTextField AnioFechaTerminoJTextField;
    private javax.swing.JCheckBox ConfirmadoJCheckBox;
    private javax.swing.JCheckBox DescartadoJCheckBox;
    private javax.swing.JTextField DiaFechaInicioJTextField;
    private javax.swing.JTextField DiaFechaTerminoJTextField;
    private javax.swing.JCheckBox ExceptuadoJCheckBox;
    private javax.swing.JLabel FechaInicioJLabel;
    private javax.swing.JLabel FechaTerminoJLabel;
    private javax.swing.JCheckBox GESJCheckBox;
    private javax.swing.JLabel IPDJLabel;
    private javax.swing.JTextField MesFechaInicioJTextField;
    private javax.swing.JTextField MesFechaTerminoJTextField;
    private javax.swing.JCheckBox NoGesJCheckBox;
    private javax.swing.JCheckBox NoJCheckBox;
    private javax.swing.JLabel NombreCompletoJLabel;
    private javax.swing.JTextField NombreCompletoJTextField;
    private javax.swing.JLabel NotificacionPacienteGesJLabel;
    private javax.swing.JLabel ObservacionJLabel;
    private javax.swing.JScrollPane ObservacionJScrollPane;
    private javax.swing.JTextArea ObservacionJTextArea;
    private javax.swing.JLabel PatologiasJLabel;
    private javax.swing.JTextField PatologiasJTextField;
    private javax.swing.JLabel RUTJLabel;
    private javax.swing.JTextField RUTJTextField1;
    private javax.swing.JTextField RUTJTextField2;
    private javax.swing.JCheckBox SiJCheckBox;
    private javax.swing.JButton VolverJButton;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JSeparator jSeparator1;
    private javax.swing.JSeparator jSeparator2;
    private javax.swing.JSeparator jSeparator3;
    private javax.swing.JSeparator jSeparator4;
    // End of variables declaration//GEN-END:variables
}
