/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package ufro.proyectoges.vista;

/**
 *
 * @author Roald
 */
public class Menu extends javax.swing.JFrame {

    /**
     * Creates new form Menu
     */
    public Menu() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        TituloJLabel = new javax.swing.JLabel();
        MenuJLabel = new javax.swing.JLabel();
        IngresoPacientesJButton = new javax.swing.JButton();
        BusquedaPacientesJButton = new javax.swing.JButton();
        DescargaBaseDatosJButton = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setTitle("ProyectoGES - Menu");
        setResizable(false);

        TituloJLabel.setFont(new java.awt.Font("Dialog", 0, 28)); // NOI18N
        TituloJLabel.setText("SIGGES");

        MenuJLabel.setFont(new java.awt.Font("Dialog", 0, 18)); // NOI18N
        MenuJLabel.setText("MENU");

        IngresoPacientesJButton.setText("Ingreso de Casos de Pacientes");
        IngresoPacientesJButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                IngresoPacientesJButtonActionPerformed(evt);
            }
        });

        BusquedaPacientesJButton.setText("Busqueda de Casos de Pacientes");
        BusquedaPacientesJButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BusquedaPacientesJButtonActionPerformed(evt);
            }
        });

        DescargaBaseDatosJButton.setText("Descarga de Base de Datos");
        DescargaBaseDatosJButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                DescargaBaseDatosJButtonActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap(122, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(BusquedaPacientesJButton, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(IngresoPacientesJButton, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(DescargaBaseDatosJButton, javax.swing.GroupLayout.PREFERRED_SIZE, 197, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(117, 117, 117))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addComponent(TituloJLabel)
                        .addGap(158, 158, 158))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addComponent(MenuJLabel)
                        .addGap(184, 184, 184))))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(26, 26, 26)
                .addComponent(TituloJLabel)
                .addGap(41, 41, 41)
                .addComponent(MenuJLabel)
                .addGap(47, 47, 47)
                .addComponent(IngresoPacientesJButton, javax.swing.GroupLayout.PREFERRED_SIZE, 51, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(34, 34, 34)
                .addComponent(BusquedaPacientesJButton, javax.swing.GroupLayout.PREFERRED_SIZE, 46, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(39, 39, 39)
                .addComponent(DescargaBaseDatosJButton, javax.swing.GroupLayout.PREFERRED_SIZE, 43, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(49, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void IngresoPacientesJButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_IngresoPacientesJButtonActionPerformed
        // TODO add your handling code here:
        new IngresoCasoPaciente().setVisible(true);
        this.dispose();
    }//GEN-LAST:event_IngresoPacientesJButtonActionPerformed

    private void BusquedaPacientesJButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BusquedaPacientesJButtonActionPerformed
        new BusquedaPaciente().setVisible(true);
        this.dispose();
        // TODO add your handling code here:
    }//GEN-LAST:event_BusquedaPacientesJButtonActionPerformed

    private void DescargaBaseDatosJButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_DescargaBaseDatosJButtonActionPerformed
        // TODO add your handling code here:
        new DescargabaseDatos().setVisible(true);
        this.dispose();
    }//GEN-LAST:event_DescargaBaseDatosJButtonActionPerformed

    /**
     * @param args the command line arguments
     */

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton BusquedaPacientesJButton;
    private javax.swing.JButton DescargaBaseDatosJButton;
    private javax.swing.JButton IngresoPacientesJButton;
    private javax.swing.JLabel MenuJLabel;
    private javax.swing.JLabel TituloJLabel;
    // End of variables declaration//GEN-END:variables
}
